version: 2


defaults: &defaults
  docker:
    - image: circleci/python:3.8.10
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      sudo pip install --upgrade pip
      pip install --user tox

jobs:
  test:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Running app tests
          command: |
            tox
  build_package:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project
      - *prepare_venv
      - run:
          name: build package
          command: |
            python3 -m pip install --upgrade build
            python3 -m build

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build_package
